// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ImgSyncerClient is the client API for ImgSyncer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImgSyncerClient interface {
	SetDirectoryType(ctx context.Context, in *SetDirectoryTypeRequest, opts ...grpc.CallOption) (*SetDirectoryTypeResponse, error)
	ListByDate(ctx context.Context, in *ListByDateRequest, opts ...grpc.CallOption) (*ListByDateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	FilterNotUploaded(ctx context.Context, opts ...grpc.CallOption) (ImgSyncer_FilterNotUploadedClient, error)
	// Album Management
	ListAlbums(ctx context.Context, in *ListAlbumsRequest, opts ...grpc.CallOption) (*ListAlbumsResponse, error)
	CreateAlbum(ctx context.Context, in *CreateAlbumRequest, opts ...grpc.CallOption) (*CreateAlbumResponse, error)
	DeleteAlbum(ctx context.Context, in *DeleteAlbumRequest, opts ...grpc.CallOption) (*DeleteAlbumResponse, error)
	RenameAlbum(ctx context.Context, in *RenameAlbumRequest, opts ...grpc.CallOption) (*RenameAlbumResponse, error)
	MoveAssets(ctx context.Context, in *MoveAssetsRequest, opts ...grpc.CallOption) (*MoveAssetsResponse, error)
	// SAMBA Drive
	SetDriveSMB(ctx context.Context, in *SetDriveSMBRequest, opts ...grpc.CallOption) (*SetDriveSMBResponse, error)
	ListDriveSMBShares(ctx context.Context, in *ListDriveSMBSharesRequest, opts ...grpc.CallOption) (*ListDriveSMBSharesResponse, error)
	ListDriveSMBDir(ctx context.Context, in *ListDriveSMBDirRequest, opts ...grpc.CallOption) (*ListDriveSMBDirResponse, error)
	SetDriveSMBShare(ctx context.Context, in *SetDriveSMBShareRequest, opts ...grpc.CallOption) (*SetDriveSMBShareResponse, error)
	// Webdav Drive
	SetDriveWebdav(ctx context.Context, in *SetDriveWebdavRequest, opts ...grpc.CallOption) (*SetDriveWebdavResponse, error)
	ListDriveWebdavDir(ctx context.Context, in *ListDriveWebdavDirRequest, opts ...grpc.CallOption) (*ListDriveWebdavDirResponse, error)
	// NFS Drive
	SetDriveNFS(ctx context.Context, in *SetDriveNFSRequest, opts ...grpc.CallOption) (*SetDriveNFSResponse, error)
	ListDriveNFSDir(ctx context.Context, in *ListDriveNFSDirRequest, opts ...grpc.CallOption) (*ListDriveNFSDirResponse, error)
	// TODO(open-source): 补齐更多公有云盘后端 (待开源实现):
	// rpc SetDriveBaiduNetDisk (SetDriveBaiduNetDiskRequest) returns (SetDriveBaiduNetDiskResponse) {}
	// rpc StartBaiduNetdiskLogin (StartBaiduNetdiskLoginRequest) returns (StartBaiduNetdiskLoginResponse) {}
	// Manifest Cache & Meta Drive
	SetLocalCacheDir(ctx context.Context, in *SetLocalCacheDirRequest, opts ...grpc.CallOption) (*SetLocalCacheDirResponse, error)
	SyncManifest(ctx context.Context, in *SyncManifestRequest, opts ...grpc.CallOption) (*SyncManifestResponse, error)
	ClearMetaDrive(ctx context.Context, in *ClearMetaDriveRequest, opts ...grpc.CallOption) (*ClearMetaDriveResponse, error)
	RebuildManifest(ctx context.Context, in *RebuildManifestRequest, opts ...grpc.CallOption) (*RebuildManifestResponse, error)
	// Ping
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type imgSyncerClient struct {
	cc grpc.ClientConnInterface
}

func NewImgSyncerClient(cc grpc.ClientConnInterface) ImgSyncerClient {
	return &imgSyncerClient{cc}
}

func (c *imgSyncerClient) SetDirectoryType(ctx context.Context, in *SetDirectoryTypeRequest, opts ...grpc.CallOption) (*SetDirectoryTypeResponse, error) {
	out := new(SetDirectoryTypeResponse)
	err := c.cc.Invoke(ctx, "/img_syncer.ImgSyncer/SetDirectoryType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) ListByDate(ctx context.Context, in *ListByDateRequest, opts ...grpc.CallOption) (*ListByDateResponse, error) {
	out := new(ListByDateResponse)
	err := c.cc.Invoke(ctx, "/img_syncer.ImgSyncer/ListByDate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/img_syncer.ImgSyncer/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) FilterNotUploaded(ctx context.Context, opts ...grpc.CallOption) (ImgSyncer_FilterNotUploadedClient, error) {
	stream, err := c.cc.NewStream(ctx, &ImgSyncer_ServiceDesc.Streams[0], "/img_syncer.ImgSyncer/FilterNotUploaded", opts...)
	if err != nil {
		return nil, err
	}
	x := &imgSyncerFilterNotUploadedClient{stream}
	return x, nil
}

type ImgSyncer_FilterNotUploadedClient interface {
	Send(*FilterNotUploadedRequest) error
	Recv() (*FilterNotUploadedResponse, error)
	grpc.ClientStream
}

type imgSyncerFilterNotUploadedClient struct {
	grpc.ClientStream
}

func (x *imgSyncerFilterNotUploadedClient) Send(m *FilterNotUploadedRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *imgSyncerFilterNotUploadedClient) Recv() (*FilterNotUploadedResponse, error) {
	m := new(FilterNotUploadedResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *imgSyncerClient) ListAlbums(ctx context.Context, in *ListAlbumsRequest, opts ...grpc.CallOption) (*ListAlbumsResponse, error) {
	out := new(ListAlbumsResponse)
	err := c.cc.Invoke(ctx, "/img_syncer.ImgSyncer/ListAlbums", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) CreateAlbum(ctx context.Context, in *CreateAlbumRequest, opts ...grpc.CallOption) (*CreateAlbumResponse, error) {
	out := new(CreateAlbumResponse)
	err := c.cc.Invoke(ctx, "/img_syncer.ImgSyncer/CreateAlbum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) DeleteAlbum(ctx context.Context, in *DeleteAlbumRequest, opts ...grpc.CallOption) (*DeleteAlbumResponse, error) {
	out := new(DeleteAlbumResponse)
	err := c.cc.Invoke(ctx, "/img_syncer.ImgSyncer/DeleteAlbum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) RenameAlbum(ctx context.Context, in *RenameAlbumRequest, opts ...grpc.CallOption) (*RenameAlbumResponse, error) {
	out := new(RenameAlbumResponse)
	err := c.cc.Invoke(ctx, "/img_syncer.ImgSyncer/RenameAlbum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) MoveAssets(ctx context.Context, in *MoveAssetsRequest, opts ...grpc.CallOption) (*MoveAssetsResponse, error) {
	out := new(MoveAssetsResponse)
	err := c.cc.Invoke(ctx, "/img_syncer.ImgSyncer/MoveAssets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) SetDriveSMB(ctx context.Context, in *SetDriveSMBRequest, opts ...grpc.CallOption) (*SetDriveSMBResponse, error) {
	out := new(SetDriveSMBResponse)
	err := c.cc.Invoke(ctx, "/img_syncer.ImgSyncer/SetDriveSMB", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) ListDriveSMBShares(ctx context.Context, in *ListDriveSMBSharesRequest, opts ...grpc.CallOption) (*ListDriveSMBSharesResponse, error) {
	out := new(ListDriveSMBSharesResponse)
	err := c.cc.Invoke(ctx, "/img_syncer.ImgSyncer/ListDriveSMBShares", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) ListDriveSMBDir(ctx context.Context, in *ListDriveSMBDirRequest, opts ...grpc.CallOption) (*ListDriveSMBDirResponse, error) {
	out := new(ListDriveSMBDirResponse)
	err := c.cc.Invoke(ctx, "/img_syncer.ImgSyncer/ListDriveSMBDir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) SetDriveSMBShare(ctx context.Context, in *SetDriveSMBShareRequest, opts ...grpc.CallOption) (*SetDriveSMBShareResponse, error) {
	out := new(SetDriveSMBShareResponse)
	err := c.cc.Invoke(ctx, "/img_syncer.ImgSyncer/SetDriveSMBShare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) SetDriveWebdav(ctx context.Context, in *SetDriveWebdavRequest, opts ...grpc.CallOption) (*SetDriveWebdavResponse, error) {
	out := new(SetDriveWebdavResponse)
	err := c.cc.Invoke(ctx, "/img_syncer.ImgSyncer/SetDriveWebdav", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) ListDriveWebdavDir(ctx context.Context, in *ListDriveWebdavDirRequest, opts ...grpc.CallOption) (*ListDriveWebdavDirResponse, error) {
	out := new(ListDriveWebdavDirResponse)
	err := c.cc.Invoke(ctx, "/img_syncer.ImgSyncer/ListDriveWebdavDir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) SetDriveNFS(ctx context.Context, in *SetDriveNFSRequest, opts ...grpc.CallOption) (*SetDriveNFSResponse, error) {
	out := new(SetDriveNFSResponse)
	err := c.cc.Invoke(ctx, "/img_syncer.ImgSyncer/SetDriveNFS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) ListDriveNFSDir(ctx context.Context, in *ListDriveNFSDirRequest, opts ...grpc.CallOption) (*ListDriveNFSDirResponse, error) {
	out := new(ListDriveNFSDirResponse)
	err := c.cc.Invoke(ctx, "/img_syncer.ImgSyncer/ListDriveNFSDir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) SetLocalCacheDir(ctx context.Context, in *SetLocalCacheDirRequest, opts ...grpc.CallOption) (*SetLocalCacheDirResponse, error) {
	out := new(SetLocalCacheDirResponse)
	err := c.cc.Invoke(ctx, "/img_syncer.ImgSyncer/SetLocalCacheDir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) SyncManifest(ctx context.Context, in *SyncManifestRequest, opts ...grpc.CallOption) (*SyncManifestResponse, error) {
	out := new(SyncManifestResponse)
	err := c.cc.Invoke(ctx, "/img_syncer.ImgSyncer/SyncManifest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) ClearMetaDrive(ctx context.Context, in *ClearMetaDriveRequest, opts ...grpc.CallOption) (*ClearMetaDriveResponse, error) {
	out := new(ClearMetaDriveResponse)
	err := c.cc.Invoke(ctx, "/img_syncer.ImgSyncer/ClearMetaDrive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) RebuildManifest(ctx context.Context, in *RebuildManifestRequest, opts ...grpc.CallOption) (*RebuildManifestResponse, error) {
	out := new(RebuildManifestResponse)
	err := c.cc.Invoke(ctx, "/img_syncer.ImgSyncer/RebuildManifest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/img_syncer.ImgSyncer/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImgSyncerServer is the server API for ImgSyncer service.
// All implementations must embed UnimplementedImgSyncerServer
// for forward compatibility
type ImgSyncerServer interface {
	SetDirectoryType(context.Context, *SetDirectoryTypeRequest) (*SetDirectoryTypeResponse, error)
	ListByDate(context.Context, *ListByDateRequest) (*ListByDateResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	FilterNotUploaded(ImgSyncer_FilterNotUploadedServer) error
	// Album Management
	ListAlbums(context.Context, *ListAlbumsRequest) (*ListAlbumsResponse, error)
	CreateAlbum(context.Context, *CreateAlbumRequest) (*CreateAlbumResponse, error)
	DeleteAlbum(context.Context, *DeleteAlbumRequest) (*DeleteAlbumResponse, error)
	RenameAlbum(context.Context, *RenameAlbumRequest) (*RenameAlbumResponse, error)
	MoveAssets(context.Context, *MoveAssetsRequest) (*MoveAssetsResponse, error)
	// SAMBA Drive
	SetDriveSMB(context.Context, *SetDriveSMBRequest) (*SetDriveSMBResponse, error)
	ListDriveSMBShares(context.Context, *ListDriveSMBSharesRequest) (*ListDriveSMBSharesResponse, error)
	ListDriveSMBDir(context.Context, *ListDriveSMBDirRequest) (*ListDriveSMBDirResponse, error)
	SetDriveSMBShare(context.Context, *SetDriveSMBShareRequest) (*SetDriveSMBShareResponse, error)
	// Webdav Drive
	SetDriveWebdav(context.Context, *SetDriveWebdavRequest) (*SetDriveWebdavResponse, error)
	ListDriveWebdavDir(context.Context, *ListDriveWebdavDirRequest) (*ListDriveWebdavDirResponse, error)
	// NFS Drive
	SetDriveNFS(context.Context, *SetDriveNFSRequest) (*SetDriveNFSResponse, error)
	ListDriveNFSDir(context.Context, *ListDriveNFSDirRequest) (*ListDriveNFSDirResponse, error)
	// TODO(open-source): 补齐更多公有云盘后端 (待开源实现):
	// rpc SetDriveBaiduNetDisk (SetDriveBaiduNetDiskRequest) returns (SetDriveBaiduNetDiskResponse) {}
	// rpc StartBaiduNetdiskLogin (StartBaiduNetdiskLoginRequest) returns (StartBaiduNetdiskLoginResponse) {}
	// Manifest Cache & Meta Drive
	SetLocalCacheDir(context.Context, *SetLocalCacheDirRequest) (*SetLocalCacheDirResponse, error)
	SyncManifest(context.Context, *SyncManifestRequest) (*SyncManifestResponse, error)
	ClearMetaDrive(context.Context, *ClearMetaDriveRequest) (*ClearMetaDriveResponse, error)
	RebuildManifest(context.Context, *RebuildManifestRequest) (*RebuildManifestResponse, error)
	// Ping
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedImgSyncerServer()
}

// UnimplementedImgSyncerServer must be embedded to have forward compatible implementations.
type UnimplementedImgSyncerServer struct {
}

func (UnimplementedImgSyncerServer) SetDirectoryType(context.Context, *SetDirectoryTypeRequest) (*SetDirectoryTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDirectoryType not implemented")
}
func (UnimplementedImgSyncerServer) ListByDate(context.Context, *ListByDateRequest) (*ListByDateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListByDate not implemented")
}
func (UnimplementedImgSyncerServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedImgSyncerServer) FilterNotUploaded(ImgSyncer_FilterNotUploadedServer) error {
	return status.Errorf(codes.Unimplemented, "method FilterNotUploaded not implemented")
}
func (UnimplementedImgSyncerServer) ListAlbums(context.Context, *ListAlbumsRequest) (*ListAlbumsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAlbums not implemented")
}
func (UnimplementedImgSyncerServer) CreateAlbum(context.Context, *CreateAlbumRequest) (*CreateAlbumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAlbum not implemented")
}
func (UnimplementedImgSyncerServer) DeleteAlbum(context.Context, *DeleteAlbumRequest) (*DeleteAlbumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAlbum not implemented")
}
func (UnimplementedImgSyncerServer) RenameAlbum(context.Context, *RenameAlbumRequest) (*RenameAlbumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenameAlbum not implemented")
}
func (UnimplementedImgSyncerServer) MoveAssets(context.Context, *MoveAssetsRequest) (*MoveAssetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveAssets not implemented")
}
func (UnimplementedImgSyncerServer) SetDriveSMB(context.Context, *SetDriveSMBRequest) (*SetDriveSMBResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDriveSMB not implemented")
}
func (UnimplementedImgSyncerServer) ListDriveSMBShares(context.Context, *ListDriveSMBSharesRequest) (*ListDriveSMBSharesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDriveSMBShares not implemented")
}
func (UnimplementedImgSyncerServer) ListDriveSMBDir(context.Context, *ListDriveSMBDirRequest) (*ListDriveSMBDirResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDriveSMBDir not implemented")
}
func (UnimplementedImgSyncerServer) SetDriveSMBShare(context.Context, *SetDriveSMBShareRequest) (*SetDriveSMBShareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDriveSMBShare not implemented")
}
func (UnimplementedImgSyncerServer) SetDriveWebdav(context.Context, *SetDriveWebdavRequest) (*SetDriveWebdavResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDriveWebdav not implemented")
}
func (UnimplementedImgSyncerServer) ListDriveWebdavDir(context.Context, *ListDriveWebdavDirRequest) (*ListDriveWebdavDirResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDriveWebdavDir not implemented")
}
func (UnimplementedImgSyncerServer) SetDriveNFS(context.Context, *SetDriveNFSRequest) (*SetDriveNFSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDriveNFS not implemented")
}
func (UnimplementedImgSyncerServer) ListDriveNFSDir(context.Context, *ListDriveNFSDirRequest) (*ListDriveNFSDirResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDriveNFSDir not implemented")
}
func (UnimplementedImgSyncerServer) SetLocalCacheDir(context.Context, *SetLocalCacheDirRequest) (*SetLocalCacheDirResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLocalCacheDir not implemented")
}
func (UnimplementedImgSyncerServer) SyncManifest(context.Context, *SyncManifestRequest) (*SyncManifestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncManifest not implemented")
}
func (UnimplementedImgSyncerServer) ClearMetaDrive(context.Context, *ClearMetaDriveRequest) (*ClearMetaDriveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearMetaDrive not implemented")
}
func (UnimplementedImgSyncerServer) RebuildManifest(context.Context, *RebuildManifestRequest) (*RebuildManifestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RebuildManifest not implemented")
}
func (UnimplementedImgSyncerServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedImgSyncerServer) mustEmbedUnimplementedImgSyncerServer() {}

// UnsafeImgSyncerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImgSyncerServer will
// result in compilation errors.
type UnsafeImgSyncerServer interface {
	mustEmbedUnimplementedImgSyncerServer()
}

func RegisterImgSyncerServer(s grpc.ServiceRegistrar, srv ImgSyncerServer) {
	s.RegisterService(&ImgSyncer_ServiceDesc, srv)
}

func _ImgSyncer_SetDirectoryType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDirectoryTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).SetDirectoryType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/img_syncer.ImgSyncer/SetDirectoryType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).SetDirectoryType(ctx, req.(*SetDirectoryTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_ListByDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListByDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).ListByDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/img_syncer.ImgSyncer/ListByDate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).ListByDate(ctx, req.(*ListByDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/img_syncer.ImgSyncer/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_FilterNotUploaded_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ImgSyncerServer).FilterNotUploaded(&imgSyncerFilterNotUploadedServer{stream})
}

type ImgSyncer_FilterNotUploadedServer interface {
	Send(*FilterNotUploadedResponse) error
	Recv() (*FilterNotUploadedRequest, error)
	grpc.ServerStream
}

type imgSyncerFilterNotUploadedServer struct {
	grpc.ServerStream
}

func (x *imgSyncerFilterNotUploadedServer) Send(m *FilterNotUploadedResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *imgSyncerFilterNotUploadedServer) Recv() (*FilterNotUploadedRequest, error) {
	m := new(FilterNotUploadedRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ImgSyncer_ListAlbums_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlbumsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).ListAlbums(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/img_syncer.ImgSyncer/ListAlbums",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).ListAlbums(ctx, req.(*ListAlbumsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_CreateAlbum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAlbumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).CreateAlbum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/img_syncer.ImgSyncer/CreateAlbum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).CreateAlbum(ctx, req.(*CreateAlbumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_DeleteAlbum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAlbumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).DeleteAlbum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/img_syncer.ImgSyncer/DeleteAlbum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).DeleteAlbum(ctx, req.(*DeleteAlbumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_RenameAlbum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameAlbumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).RenameAlbum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/img_syncer.ImgSyncer/RenameAlbum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).RenameAlbum(ctx, req.(*RenameAlbumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_MoveAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveAssetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).MoveAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/img_syncer.ImgSyncer/MoveAssets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).MoveAssets(ctx, req.(*MoveAssetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_SetDriveSMB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDriveSMBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).SetDriveSMB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/img_syncer.ImgSyncer/SetDriveSMB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).SetDriveSMB(ctx, req.(*SetDriveSMBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_ListDriveSMBShares_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDriveSMBSharesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).ListDriveSMBShares(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/img_syncer.ImgSyncer/ListDriveSMBShares",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).ListDriveSMBShares(ctx, req.(*ListDriveSMBSharesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_ListDriveSMBDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDriveSMBDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).ListDriveSMBDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/img_syncer.ImgSyncer/ListDriveSMBDir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).ListDriveSMBDir(ctx, req.(*ListDriveSMBDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_SetDriveSMBShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDriveSMBShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).SetDriveSMBShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/img_syncer.ImgSyncer/SetDriveSMBShare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).SetDriveSMBShare(ctx, req.(*SetDriveSMBShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_SetDriveWebdav_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDriveWebdavRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).SetDriveWebdav(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/img_syncer.ImgSyncer/SetDriveWebdav",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).SetDriveWebdav(ctx, req.(*SetDriveWebdavRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_ListDriveWebdavDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDriveWebdavDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).ListDriveWebdavDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/img_syncer.ImgSyncer/ListDriveWebdavDir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).ListDriveWebdavDir(ctx, req.(*ListDriveWebdavDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_SetDriveNFS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDriveNFSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).SetDriveNFS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/img_syncer.ImgSyncer/SetDriveNFS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).SetDriveNFS(ctx, req.(*SetDriveNFSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_ListDriveNFSDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDriveNFSDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).ListDriveNFSDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/img_syncer.ImgSyncer/ListDriveNFSDir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).ListDriveNFSDir(ctx, req.(*ListDriveNFSDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_SetLocalCacheDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLocalCacheDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).SetLocalCacheDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/img_syncer.ImgSyncer/SetLocalCacheDir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).SetLocalCacheDir(ctx, req.(*SetLocalCacheDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_SyncManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).SyncManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/img_syncer.ImgSyncer/SyncManifest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).SyncManifest(ctx, req.(*SyncManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_ClearMetaDrive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearMetaDriveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).ClearMetaDrive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/img_syncer.ImgSyncer/ClearMetaDrive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).ClearMetaDrive(ctx, req.(*ClearMetaDriveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_RebuildManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebuildManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).RebuildManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/img_syncer.ImgSyncer/RebuildManifest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).RebuildManifest(ctx, req.(*RebuildManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/img_syncer.ImgSyncer/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImgSyncer_ServiceDesc is the grpc.ServiceDesc for ImgSyncer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImgSyncer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "img_syncer.ImgSyncer",
	HandlerType: (*ImgSyncerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetDirectoryType",
			Handler:    _ImgSyncer_SetDirectoryType_Handler,
		},
		{
			MethodName: "ListByDate",
			Handler:    _ImgSyncer_ListByDate_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ImgSyncer_Delete_Handler,
		},
		{
			MethodName: "ListAlbums",
			Handler:    _ImgSyncer_ListAlbums_Handler,
		},
		{
			MethodName: "CreateAlbum",
			Handler:    _ImgSyncer_CreateAlbum_Handler,
		},
		{
			MethodName: "DeleteAlbum",
			Handler:    _ImgSyncer_DeleteAlbum_Handler,
		},
		{
			MethodName: "RenameAlbum",
			Handler:    _ImgSyncer_RenameAlbum_Handler,
		},
		{
			MethodName: "MoveAssets",
			Handler:    _ImgSyncer_MoveAssets_Handler,
		},
		{
			MethodName: "SetDriveSMB",
			Handler:    _ImgSyncer_SetDriveSMB_Handler,
		},
		{
			MethodName: "ListDriveSMBShares",
			Handler:    _ImgSyncer_ListDriveSMBShares_Handler,
		},
		{
			MethodName: "ListDriveSMBDir",
			Handler:    _ImgSyncer_ListDriveSMBDir_Handler,
		},
		{
			MethodName: "SetDriveSMBShare",
			Handler:    _ImgSyncer_SetDriveSMBShare_Handler,
		},
		{
			MethodName: "SetDriveWebdav",
			Handler:    _ImgSyncer_SetDriveWebdav_Handler,
		},
		{
			MethodName: "ListDriveWebdavDir",
			Handler:    _ImgSyncer_ListDriveWebdavDir_Handler,
		},
		{
			MethodName: "SetDriveNFS",
			Handler:    _ImgSyncer_SetDriveNFS_Handler,
		},
		{
			MethodName: "ListDriveNFSDir",
			Handler:    _ImgSyncer_ListDriveNFSDir_Handler,
		},
		{
			MethodName: "SetLocalCacheDir",
			Handler:    _ImgSyncer_SetLocalCacheDir_Handler,
		},
		{
			MethodName: "SyncManifest",
			Handler:    _ImgSyncer_SyncManifest_Handler,
		},
		{
			MethodName: "ClearMetaDrive",
			Handler:    _ImgSyncer_ClearMetaDrive_Handler,
		},
		{
			MethodName: "RebuildManifest",
			Handler:    _ImgSyncer_RebuildManifest_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _ImgSyncer_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FilterNotUploaded",
			Handler:       _ImgSyncer_FilterNotUploaded_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/img_syncer.proto",
}
